services:
  db:
    image: postgres:17-alpine
    container_name: fiber_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password123}
      POSTGRES_DB: ${DB_NAME:-finance_db}
    ports:
      - "5432:5432"
    networks:
      - finance_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: fiber_api
    restart: always
    environment:
      DB_HOST: fiber_postgres # Phải trùng với container_name của DB hay hostname trong network
      DB_PORT: 5432
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-password123}
      DB_NAME: ${DB_NAME:-finance_db}
    networks:
      - finance_network
    ports:
      - "3000:3000"

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    container_name: fiber_admin
    restart: always
    depends_on:
      - api
    networks:
      - finance_network
    ports:
      - "8080:80"

networks:
  finance_network:
    external: true

volumes:
  postgres_data: